
log = [
    {'Date': "2022/8/1", "Note": "I have completed the first draft of my script, and sent it to Ms.K for review and feedbacks", "Footage": "img/logimg/image20.png"},
    {'Date': "2022/8/2", "Note": "I have received the feedbacks from Ms.K ", "Footage": "img/logimg/image1.png"},
    {'Date': "2022/8/3", "Note": "I wrote a short synopsis for a second draft using notepadI wrote a script in a new screenwriting tool", "Footage": ""},
    {'Date': "2022/8/6", "Note": "Continued with writing the script", "Footage": "img/logimg/image3.png"},
    {'Date': "2022/8/8", "Note": "Began writing the new scene", "Footage": ""},
    {'Date': "2022/8/9", "Note": "Began writing a new scene", "Footage": "img/logimg/image22.png"},
    {'Date': "2022/8/13", "Note": "Completed the second draft of the script", "Footage": "img/logimg/image23.png"},
    {'Date': "2022/8/14", "Note": "Added final touch and polishes to the script and sent it off to Ms.K", "Footage": "img/logimg/image12.png"},
    {'Date': "2022/8/15", "Note": "Began gathering references and creating concepts", "Footage": "img/logimg/image14.png"},
    {'Date': "2022/8/16", "Note": "Began process of creating storyboard using Blender", "Footage": "img/logimg/image7.png"},
    {'Date': "2022/8/18", "Note": "Continued working on storyboard using Blender", "Footage": "img/logimg/image10.png"},
    {"Date": "2022/8/29", "Note": "Continued working on the storyboard, and began polishing the final draft", "Footage": ""},
    {"Date": "2022/9/1", "Note": "Worked on the storyboard and completed the final script. Also finally figured out the title of the film", "Footage": "img/logimg/image5.png"},
    {"Date": "2022/9/2", "Note": "Checked in with Mr.Noonan on how to use mics for recording", "Footage": ""},
    {"Date": "2022/9/3", "Note": "Began creating form for audition", "Footage": "img/logimg/image2.png"},
    {"Date": "2022/9/4", "Note": "Worked on creating model for B.U.Z.Z.", "Footage": "img/logimg/image19.png"},
    {"Date": "2022/9/5", "Note": "Created the thumbnail, finalized the audition signup form, and submitted to the HS Daily", "Footage": "img/logimg/image18.png"},
    {"Date": "2022/9/9", "Note": "- Spoke to the teachers during the morning in the teacher lounge to convince the teachers to join the audition, and managed to get about 5 teachers to join the audition <br><br> - Hosted the audition with 8 people in total participating in it, (5 teachers, 2 students, Mr.Lobo who came to take pictures) and got pretty satisfying results, however forgot to turn off metronome in garageband for some of the candidates", "Footage": ""/*"img/logimg/image9.png"*/},
    {"Date": "2022/9/10", "Note": "- Continued on modeling Buzz <br><br>- Added <i><a href='https://www.youtube.com/watch?v=0a9qIj7kwiA'class='links'>inverse kinematics<a></i> to the BUZZ robot arm <br><br>- Began learning texturing for BUZZ <br><br>- Created BUZZ script through simple coding using python <br><br>- Began picking candidates for the voice roles", "Footage": "img/logimg/image6.png"},
    {"Date": "2022/9/11", "Note": "- Sent out emails to the people who have been chosen for the role <br><br>- Worked on texturing buzz", "Footage": "img/logimg/image15.png"},
    {"Date": "2022/9/13", "Note": "Added more rigs for extra controls and added more texture changes", "Footage": "img/logimg/image17.png"},
    {"Date": "2022/9/17", "Note": "- Purchased astronaut character model from 3d model website <br><br>- Added textures and changes <br><br>-Began adding custom models to the astronaut model", "Footage": "img/logimg/image8.png"},
    {"Date": "2022/9/18", "Note": "- Finalized the texturing and modeling for character models <br><br>- Completed first two scenes of the storyboard <br><br>- Not satisfied with the result of second scene so planning to do another iteration", "Footage": "img/logimg/image11.png"},
    {"Date": "2022/9/19", "Note": "- Added water ration to the astronaut model <br><br>- Continued working on the storyboard", "Footage": ""},
    {"Date": "2022/9/21", "Note": "Did rehearsal with Mr.Hauet and Hal, set up rehearsal time for other actors", "Footage": ""},
    {"Date": "2022/9/25", "Note": "- Began migrating personal project log into my website using Javascript <br><br>- Continued working on the storyboard", "Footage": "img/logimg/image24.png"},
    {"Date": "2022/9/26", "Note": "- Rehearsed and recorded Ms.Greaves fort the B.U.Z.Z.'s voice <br><br>- Learned dynamic paint in order to create footprints <br><br> - Continued working on the storyboard", "Footage": ""},
    {"Date": "2022/9/27", "Note": "- Recorded the voices for Mr.Hauet, Mr.Seidel, and Hal for the rest of the cast", "Footage": "img/logimg/image25.jpeg"},
    {"Date": "2022/9/28", "Note": "- Began planning out the scenes <br><br>- Contacted Mr.Quint for meeting <br><br>- Began polishing and splicing the audio", "Footage": "img/logimg/image26.png"},
    {"Date": "2022/9/29", "Note": "- Continued planning out the scenes <br><br>- Completed splicing the voice audio for Buzz and also completed Mission Control's voicelines", "Footage": "img/logimg/image27.png"},
    {"Date": "2022/9/30", "Note": "- Met with Mr.Quint for the first supervisor meeting <br><br>- Sent Email to person who works at a game company to find out if he knows people who work in animation industry that could be interviewed <br><br>- Completed editing and splicing the voice for Astronaut 2", "Footage": ""},
    {"Date": "2022/10/1", "Note": "- Completed editing and splicing the voices <br><br>- Revamped the log system which allows addition of more than one file in the footage cell", "Footage": ""},
    {"Date": "2022/10/3", "Note": "- Continued revamping the website <br><br>- Added the photos from the audition <br><br>- Added new research result section <br><br>- Reworded success criteria and began organizing citations", "Footage": "img/logimg/image28.png"},
    {"Date": "2022/10/4", "Note": "- Continued filling up the research result section <br><br>- Optimized images in the website <br><br>- Planned out a date for the meeting date <br><br>- Purchased <a class='links' href='https://www.physicaladdons.com/psa/'>Physical Starlight and Atmosphere</a> Plugin for realistic sky <br><br>- Created the main file for the film, making sure everything works as intended", "Footage": "img/logimg/image29.png"},
    {"Date": "2022/10/7", "Note": "- Met with supervisor for a meeting <br><br>- Worked on environment <br><br>- Received special request for the Astronaut 2 to have stickers for personality", "Footage": "img/logimg/image31.png"},
    {"Date": "2022/10/8", "Note": "- Continued completing the research result part <br><br>- Evaluated the time which whole project would likely take to render <br><br>- began brainstorming questions for email interview <br><br>- Continued creating the first scene", "Footage": ""},
    {"Date": "2022/10/11", "Note": "- Began editing the voice lines using DAW <br><br>- Recorded reference footage with people at school <br><br>- Continued working on creating the first scene; current render time is approximately 16~17 minutes, need to make it much shorter", "Footage":"img/logimg/image32.png"},
    {"Date": "2022/10/12", "Note": "- Continued working on voice editing <br><br>- Managed to optimize the scene to render in 6 ~ 9 minutes. However, I am not happy with how the terrain and the texture turned out. Planning on revamping them", "Footage": ""},
    {"Date": "2022/10/13", "Note": "- Revamped the terrain, and it is looking far much better. Adjusting light a bit more could be done <br><br>- Sent emails to people to interview", "Footage": "img/logimg/image33.png"},
    {"Date": "2022/10/14", "Note": "- Adjusted lightings and materials which I am satisfied with <br><br>- Optimized the scene further", "Footage": "img/logimg/image34.png"},
    {"Date": "2022/10/17", "Note": "- Continued working on the animations; looking currently into NLA tracker to evaluate if they will be useful for this project <br><br>- Terrains had difficulties creating footsteps/trails so added more vertices for it to work. While it did, it slowed the whole project to the point where it was unusable and was frying my computer. Decided to revert the changes, and rely on smoke simulations to convey the trail instead <br><br>- Sent an email to one of the interviewee to arrange a time for an interview", "Footage": ""},
    {"Date": "2022/10/18", "Note": "- Continued animating <br><br> Completed research and source evaluation for resources online; Preparing for interviews in order to fully complete the research phase", "Footage": "img/logimg/image35.png"}
];

//NOTE: Multiple notes should be resolved with <br><br>
